# Generated by Django 2.0.4 on 2018-12-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medunoyeeniscrum', '0002_auto_20181214_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumgoal',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
