# Generated by Django 2.0.4 on 2018-12-18 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medunoyeeniscrum', '0003_scrumgoal_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumgoal',
            options={'ordering': ['-id']},
        ),
    ]
